development:
  adapter: postgresql
  host: localhost
  username: fpomerantz
  password: 
  database: app-dev

test:
  adapter: postgresql
  host: localhost
  username: fpomerantz
  password: 
  database: app-dev